package clasesHibernate;
// Generated 15-nov-2016 9:41:01 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * Carrera generated by hbm2java
 */
public class Carrera implements java.io.Serializable {

	private String nombre;
	private Usuarioorganizador usuarioorganizador;
	private int distancia;
	private int desnivel;
	private int precio;
	private Date fecha;
	private String lugar;

	public Carrera() {
	}

	public Carrera(String nombre, Usuarioorganizador usuarioorganizador, int distancia, int desnivel, int precio,
			Date fecha, String lugar) {
		this.nombre = nombre;
		this.usuarioorganizador = usuarioorganizador;
		this.distancia = distancia;
		this.desnivel = desnivel;
		this.precio = precio;
		this.fecha = fecha;
		this.lugar = lugar;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Usuarioorganizador getUsuarioorganizador() {
		return this.usuarioorganizador;
	}

	public void setUsuarioorganizador(Usuarioorganizador usuarioorganizador) {
		this.usuarioorganizador = usuarioorganizador;
	}

	public int getDistancia() {
		return this.distancia;
	}

	public void setDistancia(int distancia) {
		this.distancia = distancia;
	}

	public int getDesnivel() {
		return this.desnivel;
	}

	public void setDesnivel(int desnivel) {
		this.desnivel = desnivel;
	}

	public int getPrecio() {
		return this.precio;
	}

	public void setPrecio(int precio) {
		this.precio = precio;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

}
