package clasesHibernate;
// Generated 15-nov-2016 9:41:01 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarioorganizador generated by hbm2java
 */
public class Usuarioorganizador implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String apellidos;
	private String email;
	private String password;
	private String direccion;
	private int telefono;
	private String club;
	private Set<Carrera> carreras = new HashSet<Carrera>(0);

	public Usuarioorganizador() {
	}

	public Usuarioorganizador(String nombre, String apellidos, String email, String password, String direccion,
			int telefono, String club) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.password = password;
		this.direccion = direccion;
		this.telefono = telefono;
		this.club = club;
	}

	public Usuarioorganizador(String nombre, String apellidos, String email, String password, String direccion,
			int telefono, String club, Set<Carrera> carreras) {
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.email = email;
		this.password = password;
		this.direccion = direccion;
		this.telefono = telefono;
		this.club = club;
		this.carreras = carreras;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public int getTelefono() {
		return this.telefono;
	}

	public void setTelefono(int telefono) {
		this.telefono = telefono;
	}

	public String getClub() {
		return this.club;
	}

	public void setClub(String club) {
		this.club = club;
	}

	public Set<Carrera> getCarreras() {
		return this.carreras;
	}

	public void setCarreras(Set<Carrera> carreras) {
		this.carreras = carreras;
	}

}
